### ISSUE TITLE
Dark Mode Now

### ISSUE THREAD

**Issue by Tarcontar** [isaacs/github#1861] opened 2020-10-04 20:50 UTC
- yes I used the search functionality
- yes I found the open issue about the dark mode
- you guys do not seem to care about the old issue, so I opended up a new one!

refers to #66 

Regards
Tarcontar

**Comment by andrino-meli** [comment] 2020-10-07 18:05
> * yes I used the search functionality
> * yes I found the open issue about the dark mode
> * you guys do not seem to care about the old issue, so I opended up a new one!
> 
> refers to #66
> 
> Regards
> Tarcontar

Thanks for reopening. Would be a great feature.

**Comment by EriKWDev** [comment] 2020-11-02 21:45
There's dark mode in GitHub desktop, there's dark mode in GitHub for iPad, there's dark mode for GitHub's integration in the Atom Editor, there is even dark mode in the official Android App, yet here we are...

**Comment by Mr-Steal-Your-Script** [comment] 2020-11-21 01:32
Duplicate of #66

**Comment by Tarcontar** [comment] 2020-11-21 08:19
Yes, I already mentioned that above.

**Comment by Mr-Steal-Your-Script** [comment] 2020-11-21 14:16
Duplicate issues are unneeded and uncalled for. Besides unorganizing things, there's over 100 comments in the other issue.

**Comment by Tarcontar** [comment] 2020-11-21 16:37
Well those 100+ comments did not seem to have much of an effect. Thats why i opted for creating a whole new issue, since adding the 101th comment to the old issue is somewhat pointless. Maybe if they had created 100+ issues instead this would have gathered a bit more attention.

**Comment by Mr-Steal-Your-Script** [comment] 2020-11-24 19:52
Ah, yes, creating tons of issues on an unofficial repository! That'll show 'em! 🤡

**Comment by Tarcontar** [comment] 2020-11-24 20:39
Dont worry I also created an official one

**Comment by Mennaruuk** [comment] 2020-11-25 04:01
Hope this is good news:
["**It's coming. Will be the best dark mode you ever saw.**"](https://twitter.com/natfriedman/status/1305512578311884800) - Nat Friedman, CEO of GitHub

**Comment by LazaroOnline** [comment] 2020-12-04 22:43
@Tarcontar,
> Don't worry I also created an official one

What is the official repository?
I searched for it, I just can't find it within: https://github.com/github
or maybe you were just bluffing? haha

**Comment by Tarcontar** [comment] 2020-12-04 22:48
@LazaroOnline
there you go:
https://support.github.com/ticket/personal/0/858433
Searching on only a single site is not the best method to find results...

**Comment by Mr-Steal-Your-Script** [comment] 2020-12-04 22:52
>You don't have access to this page

**Comment by Tarcontar** [comment] 2020-12-04 23:03
Can't help with that, there is no option to share it or make it public.

**Comment by Mr-Steal-Your-Script** [comment] 2020-12-08 16:46
lmao. somehow, 

    creating a support ticket == official repo issue

**Closed** 2020-12-11 06:16 UTC
