### ISSUE TITLE
Allow .age attachments to issues

### ISSUE THREAD

**Issue by xmo-odoo** [isaacs/github#2029] opened 2021-08-27 06:39 UTC
Currently, github has neither private / hidden issues (#37) nor private / hidden attachments on public issues.

[Age](https://github.com/FiloSottile/age) is a very simple and opinionated encryption tool, which as a bonus works extremely well with github: `age -R <(curl -o- https://github.com/<username>.keys) < infile > outfile` will encrypt "infile" using the user's github public keys (`-R` can be repeated for multiple recipients), allowing them to use their private github key to decrypt the file and giving nobody else access.

This means it works rather well as a way to upload attachments visible only to maintainers. Or would if age files were supported, as-is they have to be smuggled as the "cleartext" file (stripping out the `.age` extension), possibly confusing people.

**Comment by Levi-Lesches** [comment] 2021-08-27 16:17
Duplicate of #37?

**Comment by xmo-odoo** [comment] 2021-08-30 06:20
@Levi-Lesches not exactly, I'm using encrypted attachments as a work-around-ish for #37 (hence having linked to it in the description) but private attachments on public issues is useful regardless, and so is encrypted attachments in general.

**Comment by michellemerrill** [comment] 2021-09-02 16:26
Closing per https://github.com/isaacs/github/issues/2029#issuecomment-906963861 and https://github.com/isaacs/github/issues/2035

**Closed as completed by michellemerrill** 2021-09-02 16:26 UTC
