### ISSUE TITLE
Pull request displays "unknown repo" after deletion of fork

### ISSUE THREAD

**Issue by tobiasvl** [isaacs/github#168] opened 2014-04-14 20:24 UTC
I recently had [a pull request approved](https://github.com/neuf/inside/pull/1). I deleted the feature branch afterwards, as it was not needed anymore, and I also deleted the fork, because I didn't need it anymore either. Now the pull request came from an "unknown repository":

I understand that the reason is that the repo's name is retrieved dynamically and that it doesn't exist anymore when it's deleted, but this behavior is pretty jarring and I have to wonder if it's intended. I'd rather not keep old, out-of-date forks around just so past pull requests aren't "broken".

I guess there might be a privacy concern here, as deleted/private repos should probably not be publicized in any way, but seeing as the old fork's name is saved for posterity in [the merge commit message](https://github.com/neuf/inside/commit/a90cfa7dc0ccca6746eb14616f34a45e5b8527ea), that shouldn't really be a problem.

**Comment by hansfn** [comment] 2015-04-06 20:04
Just for the record: This is still an issue. I just deleted my forked repository, and the (approved) pull request is now said to come from an "unknown repository".

**Comment by DanailMinchev** [comment] 2015-05-15 18:25
Any updates on this?

**Comment by nvasilescu** [comment] 2015-06-15 20:13
still having this problem. Now i'm stuck if i don't choose another name for the repo. I deleted a repor trying to upload again as not all files seemed to upload. Now the desktop client sees the repo missing as it was deleted but can't unpublish.

**Comment by petermarcoen** [comment] 2015-07-08 13:04
+1

**Comment by raymondwanyoike** [comment] 2015-08-03 16:08
:+1:

**Comment by maximd** [comment] 2015-09-04 13:07
+1

**Comment by DanielAsher** [comment] 2015-09-09 13:10
:+1:

**Comment by dijonkitchen** [comment] 2015-10-14 15:46
+1

**Comment by brunowego** [comment] 2015-10-16 13:16
+1

**Comment by Schweinepriester** [comment] 2015-11-05 08:56
+1

**Comment by OPersian** [comment] 2015-11-12 14:37
+1

**Comment by NiklasRosenstein** [comment] 2015-12-08 17:03
+1

**Comment by ErikSwan** [comment] 2015-12-10 04:39
+1. This feels like something is broken even if it's intended behavior. I would rather the string be saved with the pull request instead of retrieved dynamically. Since I believe pull requests are stored with the upstream repo, I don't feel like this should be too difficult.

**Comment by szakharchenko** [comment] 2015-12-21 06:12
+1. Not having this encourages users to keep stale forks.

**Comment by DanielAsher** [comment] 2016-01-05 19:02
@szakharchenko +1 
agreed.

**Comment by atodorov** [comment] 2016-01-21 08:42
+1

**Comment by dr1s** [comment] 2016-01-21 10:32
+1

**Comment by vz10** [comment] 2016-01-21 11:17
+1

**Comment by TamoshaytisV** [comment] 2016-01-21 11:17
+1

**Comment by dorosh** [comment] 2016-01-21 11:18
+1

**Comment by maxsocl** [comment] 2016-01-21 11:22
+1

**Comment by AlesyaD** [comment] 2016-01-21 11:49
+1

**Comment by xahgmah** [comment] 2016-01-21 12:07
+1

**Comment by tristanbbq** [comment] 2016-01-22 20:37
+1

**Comment by jnm2** [comment] 2016-02-09 17:37
+1

**Comment by wildtron** [comment] 2016-02-23 02:29
+1

**Comment by rwestlund** [comment] 2016-02-27 06:03
+1

**Comment by MaineTim** [comment] 2016-03-06 14:01
+1

**Comment by SilentFlame** [comment] 2016-03-17 13:47
+1

**Comment by chalasr** [comment] 2016-03-18 10:28
+1

**Comment by luviiit** [comment] 2016-03-24 15:48
+1

**Comment by dakusan** [comment] 2016-03-24 16:29
+1

**Comment by kloverde** [comment] 2016-03-26 14:28
+1

**Comment by bishisht** [comment] 2016-03-28 17:31
+1

**Comment by anthonyjsmith** [comment] 2016-03-28 19:35
+1's are deprecated now: click the smiley instead!

**Comment by tobiasvl** [comment] 2016-03-28 21:32
Finally I can get *likes* on my proposals! Web 2.0

**Comment by JoaoPinheiro** [comment] 2016-04-24 13:35
+1

What's the current status on this? I have stale forks that I no longer use cluttering my list of repositories simply because of this issue.

**Comment by trevorsibanda** [comment] 2016-06-17 11:08
+1

**Comment by TPS** [comment] 2016-06-17 13:38
Has ___anyone___ here [contacted](https://github.com/contact) @GitHub?  This seems virtually bug-level territory! 😒

**Comment by tobiasvl** [comment] 2016-06-28 11:11
@TPS Yes, I contacted GitHub staff via e-mail before I opened this issue (correspondence cited in the first comments).

I nagged them again one and a half year later (and also linked them to this issue), in September 2015, and got the following reply:

>  Thanks for checking in. We don't share a public roadmap, so we don't have any updates. Appreciate the feedback though.

Others should also feel free to let them know that they want this solved. Send e-mails to support@github.com.

**Comment by TPS** [comment] 2016-06-28 16:20
@tobiasvl Sorry, somehow [I](#issuecomment-40643451) [missed](#issuecomment-40693164) [them](#issuecomment-229019738); I didn't mean to sound sound annoyed with _you_, just @GitHub! :bow:

Even saying <kbd>`deleted fork`</kbd> would be infinitely better <kbd>`unknown repository`</kbd>.

&, I'm told, using https://github.com/contact is more reliable to contact @GitHub than support@github.com (I've read a # of reports that sometimes that the e-mails bounce) but they'll send 1 e-mail confirmation & (usually) form reply.  Referring [here](#) is an excellent idea!

**Comment by eflyjason** [comment] 2016-07-20 13:37
+1

**Comment by waldyr** [comment] 2016-08-09 14:36
http://stackoverflow.com/questions/36071272/fix-unknown-repository-of-an-opened-pr-after-deleted-the-fork/38853737#38853737

**Comment by TPS** [comment] 2016-08-28 15:02
@tobiasvl  @cirosantilli @All I believe this is solved quite recently, sometime between August 3 & August 28, 2016!  (Today, I deleted a `patch-1` branch, but the closed PR kept the branch name;  the previous 1 from that date still says `unknown repository`.)

Can someone verify & close FTW? :fireworks:

**Comment by DanielAsher** [comment] 2016-08-28 15:07
I don't know whether to praise or berate GitHub for their wickedly silent address of this issue. Confusedly, Daniel

**Comment by TPS** [comment] 2016-08-28 15:24
NM, deleting the _branch_ doesn't exhibit the behavior, but deleting the _repo_ still does! :disappointed:

**Comment by chalasr** [comment] 2016-09-02 18:37
Confirmed, it isn't solved.

**Comment by jnm2** [comment] 2016-09-15 13:57
I wonder if https://platform.github.community/ is an appropriate place to bring this to GitHub's attention?

**Comment by TPS** [comment] 2016-09-15 14:24
@jnm2 Apparently, no; that's just the ß-access (for some projects _already_ being worked on) Discourse (as an aside, why _isn't_ this dogfed?!) site, but an excellent catch to add to #6!  Did you want to do so?  How did you find it, weird domain & all?

**Comment by jnm2** [comment] 2016-09-15 15:03
I'm subscribed to the GitHub blog and got [https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features).

**Comment by panpawn** [comment] 2016-12-31 11:01
+1

**Comment by coin3x** [comment] 2017-01-04 10:09
+1

**Comment by frederich** [comment] 2017-01-26 18:39
+1

**Comment by min050820** [comment] 2017-01-31 14:44
+1

**Comment by egodin** [comment] 2017-01-31 17:08
+1

**Comment by dennisvr** [comment] 2017-02-08 12:36
+1

**Comment by sudofox** [comment] 2017-02-16 21:10
+1

**Comment by NicolasLambert** [comment] 2017-02-23 12:52
+1

**Comment by Superman8218** [comment] 2017-02-28 22:33
+1

**Comment by wlsc** [comment] 2017-05-14 08:02
Any news on this issue?

**Comment by lifecrisis** [comment] 2017-05-25 19:05
Friendly ping to GitHub staff. Please fix!

**Comment by ngocthang** [comment] 2017-06-08 07:45
+1

**Comment by jnm2** [comment] 2017-06-08 14:10
@Haacked Has anyone at GitHub seen this?

**Comment by Haacked** [comment] 2017-06-08 18:26
@jnm2 They have now! :smile:

This isn't my area of responsibility, but I can certainly let others know.

And as usual, I can't promise it'll be fixed any time soon or at all. Especially since I'm not aware of why the change was made.

Also, it's not clear to me how much of a blocker this is for people or is it just an annoyance. The info is preserved in the merge commit as the poster suggested. To help prioritization, it might help to understand why this is so important to people. How is it affecting your day to day workflows. What are you trying to accomplish that you can no longer do.

Understanding that might help make the case this should be fixed above all the other issues we are currently prioritizing.

**Comment by jnm2** [comment] 2017-06-08 19:16
@Haacked There's a meta-issue here that's even more important. There is no publicly visible place for the community to request features, report bugs and discuss issues pertaining to GitHub itself. This has got to be one of the greatest ironies that could surround GitHub. 😆

Emailing support can apparently be a black hole. Because it's private communication, no one has any idea if anyone else shares the frustration or if GitHub knows about it, and GitHub can't ever feel community pressure to change something. I think that's a bit of a problem.

**Comment by jcasner** [comment] 2017-06-09 19:48
FWIW, I've dealt with this several times as employees have left organizations. I have always used the solution found at https://gist.github.com/piscisaureus/3342247 to recreate the branch in my own fork and opened a new PR addressing whatever outstanding feedback was required. Hope this helps someone else.

**Comment by her** [comment] 2017-06-18 20:38
Adding my comment here saying that it would be nice if the `unknown repository` could be populated from the merge commit message. Come on GitHub, thanks 🖤

**Comment by Thiblizz** [comment] 2017-06-30 03:22
Please GitHub, for the love of God that would be awesome! 😄

**Comment by mikaelz** [comment] 2017-07-29 06:45
+1

**Comment by hewills** [comment] 2017-08-04 23:18
+1

**Comment by erkinalp** [comment] 2017-08-05 09:12
It is done for privacy reasons.

**Comment by jnm2** [comment] 2017-08-05 16:20
You didn't have that privacy the entire time you asked people to review your PR, so why is it important afterwards? And why is the fork name even slightly a privacy concern in OSS at all?

**Comment by PredatorIWD** [comment] 2017-08-15 16:23
+3 years later

**Comment by wintonzheng** [comment] 2017-08-15 21:28
+1

**Comment by jnm2** [comment] 2017-11-01 20:33
GitHub has new community forums: https://github.community/

**Comment by fiestacasey** [comment] 2017-11-06 20:00
👍

**Comment by bertho-zero** [comment] 2017-11-27 13:21
+1

**Comment by dragetd** [comment] 2017-12-05 06:25
+1

**Comment by nothinux** [comment] 2017-12-21 06:38
+1

**Comment by AleksCore** [comment] 2017-12-26 17:41
10 years later

**Comment by bellgance** [comment] 2017-12-28 22:35
+1

**Comment by davidmenendez** [comment] 2018-01-03 17:11
+1

**Comment by Asenar** [comment] 2018-01-05 11:09
Same here :)

curl -L url-repo/pull/1.path says diff is unavailable.

If this is impossible, maybe at least a button to show a raw version of the diff would be an acceptable fallback

**Comment by chenrui333** [comment] 2018-01-15 17:06
👍

**Comment by m3esma** [comment] 2018-01-21 10:04
+1

**Comment by iSkore** [comment] 2018-03-06 18:09
+1

**Comment by micky2be** [comment] 2018-03-15 02:14
+1

**Comment by aspiers** [comment] 2018-03-19 12:53
Firstly, for the love of `$DEITY` **PLEASE STOP SPAMMING THIS ISSUE WITH +1 COMMENTS!**  Every time you do that it spams the inboxes of everyone subscribed to the issue.  If you want to register your support for this issue, or any other reaction, use [the reaction icon GitHub provided for this](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) near the top-right of the original issue description.  (And for anyone suffering from this spam, you can use @Mottie's [awesome userscript](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-issue-comments) to automatically hide the spam. See also https://github.com/isaacs/github/issues/640).

## Known workaround for this problem

With that rant out of the way, I want to highlight [one of the few useful comments on this issue](https://github.com/isaacs/github/issues/168#issuecomment-307483338), which is from @jcasner but unfortunately got buried amongst all the comment spam.  It points to [this very useful gist which explains how to work around this issue](https://gist.github.com/piscisaureus/3342247).

Again that gist is full of comments, so to save you wading through them all, here's the TL;DR:

If there is a PR displaying `unknown repository` after the fork was deleted, and you want to resurrect that PR, simply type:

    git fetch origin refs/pull/123/head:foo

substituting (if necessary) `origin` for the remote pointing at the target repo, `123` for the PR number, and `foo` for the name of the local branch you want created to point to the head of the PR.

Then you can simply `git checkout foo`, close the stale PR, and resubmit a new one which supersedes it.

* * *

<kbd>**[Please don't just react `& DON'T +1/👍-only post`: _also_ contact GitHub supporting this & report back here!](https://github.com/contact)**</kbd>

**Comment by SamuelToh** [comment] 2018-09-10 22:32
+1 for this.

**Comment by RaidAndFade** [comment] 2018-10-05 23:51
This leads to a more pronounced issue in the api where a pull requests `diff` in the api cannot be retrieved, and is always "Sorry, this diff is unavailable." even if the PR itself has clear differences in the individual commits. Not sure whether this should be a new issue of its own or a follow up of this but it's definitely related.

**Comment by hvhaugwitz** [comment] 2019-06-13 08:44
Any updates on this issue?

In the pull request overview the repo information is still available in the mouse overlay of the pull request title; so it might be easy to replace `unknown repository` with the correct repo:branch.

**Comment by iwaduarte** [comment] 2020-03-11 14:06
The message should display:
User merged (n) commits into {original} from {user: fork} no longer available.

**Comment by Caiofcas** [comment] 2020-06-28 21:35
+1

**Comment by shinriyo** [comment] 2020-09-20 22:24
unknown repository can't reborn?

**Comment by DesmondWillowbrook** [comment] 2021-01-19 17:10
Any update to the issue? It is still affecting users.

**Comment by jakesyl** [comment] 2021-01-26 00:59
+1, this is affecting lightningnetwork/lnd#4836 and lightningnetwork/lnd#4944

**Comment by botatoes** [comment] 2021-02-17 19:15
Hi All, I'm a PM at GitHub. 

We pushed out a fix for this this week. The current behavior is now:
1. You should still be able to see the repo owner/branch name 
2. Link to deleted repo is removed

**Closed** 2021-02-17 22:54 UTC
Labels: forks, implemented, merge, pull-requests, render, ui
