### ISSUE TITLE
Convert an already opened pull request to a draft

### ISSUE THREAD

**Issue by eduherminio** [isaacs/github#1640] opened 2019-08-15 14:15 UTC
Right now pull requests can be created as 'drafts'.
It would be awesome to **convert already opened pull requests to 'drafts'**.

**Comment by oprogramador** [comment] 2019-08-20 16:15
Could you modify the title `Converty an already` -> `Convert an already`

**Comment by aspiers** [comment] 2019-11-30 14:44
Duplicate of #1547

**Closed by aspiers** 2019-11-30 14:44 UTC
