### ISSUE TITLE
Split line selection

### ISSUE THREAD

**Issue by jamen** [isaacs/github#501] opened 2015-10-22 18:11 UTC
In GitHub, you can select a line of code by simply clicking the line number on the side.  You can select a block of code by shift clicking on another line...  Take this piece of code for example:

![image](https://cloud.githubusercontent.com/assets/6251703/10673765/c99f7ca6-78b4-11e5-87d4-2e1a17059b10.png)

However you cannot select separate blocks, or separate lines that aren't connected.  Here is a edited example of what I'd like to do:

![image](https://cloud.githubusercontent.com/assets/6251703/10674015/0494bd52-78b6-11e5-9ddf-725af48089df.png)

**Comment by cirosantilli** [comment] 2015-10-24 08:03
Possible duplicate of: https://github.com/isaacs/github/issues/453

**Closed by cirosantilli** 2015-10-24 08:03 UTC
