### ISSUE TITLE
Make the branch names on PR's and other places as links to branches

### ISSUE THREAD

**Issue by vipulnsward** [isaacs/github#636] opened 2016-04-05 07:03 UTC
Having these link to branch views is pretty useful, to refer to branch/status of commits on the branch after commits/changes, etc.
For example, quickly view different commits on that branch, or status of the repo on that branch.

![pr](https://cloud.githubusercontent.com/assets/567626/14273715/4062baea-fb2a-11e5-81de-6837070bfe12.jpg)

**Comment by cirosantilli** [comment] 2016-04-05 14:14
Sample URL: https://github.com/rails/rails/pull/24429

**Comment by clarkbw** [comment] 2018-03-05 22:12
duplicate of #34

**Closed by clarkbw** 2018-03-05 22:12 UTC
Labels: enhancement, ui
