### ISSUE TITLE
GitHub Pages: Generate SSL certificate for www subdomain when a custom domain is set to an apex (and vice versa)

### ISSUE THREAD

**Issue by jakejarvis** [isaacs/github#1675] opened 2019-10-11 15:28 UTC
There's a _loooooong_ discussion over at https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116 about this — incorrectly marked as "solved," of course.

When setting a custom domain on a GitHub Pages repo to a root domain, like `example.com`, a Let's Encrypt certificate for it is generated when Enforce HTTPS is enabled (obviously). But there is absolutely no way to have `www.example.com` redirect to the root/apex domain `example.com` with a valid SSL certificate as well.

It absolutely sucks having to add yet _another_ service into the mix just to get https://www.example.com to redirect to https://example.com without showing a certificate warning. It seems like a pretty safe assumption that if someone enters an apex domain then they'll want www to mirror it/redirect to it — wanting different content at @ and www is a _super_ rare edge case (and probably accidental if it does occur, to be honest). 

Certain domain registrars and/or DNS providers can do this for free (Google Domains, Cloudflare, etc.) but I'd love to keep things consistent re: hosting...and, of course, my personal DNS provider and many others charge extra for this. 

Please add `www` as an alt name on the LE certificate by default if the user inputs an apex domain as the custom domain!

**Comment by gotexis** [comment] 2019-10-31 05:26
meanwhile, for a subdomain, e.g.

`subdomain.mydomain.com`

When pointing this to githubuser.github.io/repo_name, it doesnt seem taht the issued SSRL cert works for me.

**Comment by jakejarvis** [comment] 2019-10-31 17:45
@gotexis Is your CNAME set to `githubuser.github.io/repo_name`? If so you only need to point it to `githubuser.github.io` and then GitHub figures out the repo automatically. :)

**Comment by gotexis** [comment] 2019-10-31 20:10
Hey thanks for your response. I found out the problem in my case, turn out the cert was not issued yet as it is stated in the settings, so when I visit the site I got the default within cert which is not valid for custom domain.

I think although this was  resolved by simply waiting a bit longer, it is still a bug

**Comment by alkisg** [comment] 2019-11-21 18:31
Same here:

- https://epoptes.org = OK, https://www.epoptes.org = wrong certificate.
- https://ltsp.org = OK, https://www.ltsp.org = wrong certificate.

**Comment by anwfr** [comment] 2019-12-04 13:05
Same here: https://www.kycp.org = OK, https://kycp.org = KO

**Comment by sahilbadyal** [comment] 2019-12-08 05:13
I don't know if its the same issue or not but my certificate expires every 3 months and then it takes 2 months for automatic renewal. This really sucks.
https://sahilbadyal.com

**Comment by hlascelles** [comment] 2020-01-08 21:10
On a [github community page](https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/m-p/41680/highlight/true#M2417) a user has pasted a list of "popular websites currently broken websites to demonstrate how pervasive this issue is in practice". 

- https://www.commonmark.org/
- https://www.scikit-learn.org/
- https://www.pytorch.org/
- https://www.selenium.dev/
- https://www.rpm.org/
- https://www.webassembly.org/
- https://www.wkhtmltopdf.org/
- https://www.metaflow.org/
- https://trailofbits.com/
- https://www.microservices.io/
- https://www.semver.org/
- https://www.vue-chartjs.org/
- https://www.flutterowl.com/

**Comment by samuelkn** [comment] 2020-04-09 15:44
I think, I finally understood the recommendation of github to redirect example.com to www.example.com through DNS server. Through this, you will always land on github through your www. domain and the single SSL certificate for the custom www-domain is sufficient. 
In contrary, it has been suggested and widely accepted to redirect the naked domain (example.com) through an A entry to the IPs github. (see https://stackoverflow.com/questions/9082499/custom-domain-for-github-project-pages).
At least, it worked for me like that.

**Comment by JulioV** [comment] 2020-12-19 03:18
Since I was building my site with GA actions, I ended up deploying my `ghpages` branch with Netlify, zero issues with the SSL certificates and the apex and www domain

**Comment by dpwiese** [comment] 2021-01-09 19:32
Agreed on the importance of this request! ☝️ 

Regarding solutions given this limitation...

> Certain domain registrars and/or DNS providers can do this for free (Google Domains, Cloudflare, etc.) but I'd love to keep things consistent re: hosting...and, of course, my personal DNS provider and many others charge extra for this.

To the extent that it's helpful to others, the configuration using Google Domains DNS is via a synthetic record:

<img width="1037" alt="Screen Shot 2021-01-09 at 2 28 21 PM" src="https://user-images.githubusercontent.com/8466091/104106957-1fa67f80-5287-11eb-8e0a-aabd49b156b1.png">

It's perhaps not the ideal solution, but with this configuration anyone navigating to the `www` subdomain will get redirected to the apex, with its SSL certificate via Github pages. This has been an acceptable solution in this case, but not ideal. I hope others may find this useful.

**Comment by alimony** [comment] 2021-01-19 18:55
I got this from the GitHub support team today:

> There is good news, though: our Pages engineering team has made this a priority issue and is actually working to solve it as we speak. I don't have an ETA for when this will be done, but keep an eye on the Changelog for updates about our ability to issue both certificates for a domain in the hopefully near future.

**Comment by joaoportela** [comment] 2021-02-26 01:52
From their documentation:

«If you are using an apex domain as your custom domain, we recommend also setting up a www subdomain. If you configure the correct records for each domain type through your DNS provider, GitHub Pages will automatically create redirects between the domains. For example, if you configure www.example.com as your custom domain for your site, and you have ALIAS and CNAME records set up for the apex and www domains, then example.com will redirect to www.example.com. For more information, see "Managing a custom domain for your GitHub Pages site."»

They recommend doing things like this but it only works without HTTPS. :(

**Comment by danilo-znamerovszkij** [comment] 2021-03-01 08:51
https://gist.github.com/amingilani/332f3b5102f65a63719b2b4578b50108

The easiest way is to do it through Cloudflare

**Comment by joaoportela** [comment] 2021-03-03 12:40
What we know is:
- Having www.example.com and example.com pointing to github.io works fine without https
- If I enable https on github settings for example.com it breaks www.example.com

To solve this issue, what I did was enable **http proxy** on cloudflare **for www.example.com only**. And **enable https on cloudflare**.
This way, I don't need any rewrite rules or anything.

If I got to www.example.com it will serve the github response (that would otherwise have an invalid cert) that redirects to example.com, which was already working as expected.

It is a bit odd to have www.example.com and example.com using different certificates from different certificate authorities, but it isn't a problem.

**Comment by lubo** [comment] 2021-04-09 14:27
From [GitHub Pages can now automatically secure the www variant of your custom domain](https://github.blog/changelog/2021-04-08-github-pages-can-now-automatically-secure-the-www-variant-of-your-custom-domain/):

>When configuring a custom domain for your GitHub Pages site, we will now automatically request a certificate for both the Apex and www subdomain of that custom domain if DNS is configured appropriately.

Has anyone had a chance to test it out on an existing site?

**Comment by SVilgelm** [comment] 2021-04-09 14:29
@lubo yes, it works. I configured `www` as `CNAME` in DNS with `svilgelm.github.io` and now the url https://www.vilgelm.com works fine

**Comment by SVilgelm** [comment] 2021-04-09 15:54
> Did you literally configured it around the time you wrote your comment?

I actually changed it yesterday

**Comment by TheBoneJarmer** [comment] 2021-04-09 16:30
Hmm.. Than it should have been updated. I mean, I know it said that DNS changes take 24h to propagate but in practice it happens often faster. As I never visited your website before I doubt it is a cache thing. And I'm curtain as I just installed a now OS yesterday.

**Comment by alimony** [comment] 2021-04-09 16:46
I went to my Pages settings (the new page described in the blog post) and saw a series of dialogues telling me a new certificate was being generated:

<img width="569" alt="Screenshot 2021-04-09 at 18 38 25" src="https://user-images.githubusercontent.com/331091/114213740-abea4080-9963-11eb-85e3-18d8167bb9b6.png">

After a little while it was done, and then waiting ten more minutes or so, it now looks like it works! I can go e.g. to my website using www: https://www.scifiagenda.com/ which redirects to the apex version. Inspecting the certificate I can confirm both www and apex are included in the cert:

<img width="367" alt="Screenshot 2021-04-09 at 18 46 20" src="https://user-images.githubusercontent.com/331091/114213893-e8b63780-9963-11eb-8aac-2946bb99aa8c.png">

**Comment by SVilgelm** [comment] 2021-04-09 17:04
hmmm, I see the issue in google chrome, changed the ww to A type with same ups as for apex, will see

**Comment by alimony** [comment] 2021-04-09 17:08
Per the documentation, and what worked for me, is using `CNAME` for `www` and pointing it at `username.github.io`. In other words, exactly how you had configured it before.

**Comment by SVilgelm** [comment] 2021-04-09 17:12
yep, but it didn't work when I changed it yesterday.
Now when I changed to `A` I saw same message 

![](https://user-images.githubusercontent.com/331091/114213740-abea4080-9963-11eb-85e3-18d8167bb9b6.png)

I think the script didn't work yesterday or was overloaded, but when I changed the dns settings today, GitHub was able to see the changes and generated the certificates.

But now I see this warning:

<img width="915" alt="Screen Shot 2021-04-09 at 12 12 11 PM" src="https://user-images.githubusercontent.com/523825/114216669-d53baa00-992c-11eb-96c0-c0f9da7330fe.png">

will changed the DNS back to `CNAME`

**Comment by lubo** [comment] 2021-04-09 18:01
I've just tried it myself and it works. After changing the DNS record for my apex domain, all I had to do was to access Pages settings, where the change in DNS was detected and the message captured by @alimony was displayed. However, the message was not being displayed after refreshing the settings page. Nevertheless, it took just under 10 minutes since seeing that message.

I think this can be closed as fixed.

**Comment by SVilgelm** [comment] 2021-04-09 18:03
yep, can be closed

**Comment by TheBoneJarmer** [comment] 2021-04-09 18:47
Hey @SVilgelm, I can see your website now. Well done!

**Comment by danmana** [comment] 2021-04-13 14:13
Can confirm it works, you just have to be a bit patient after making the changes.

1. I added a `CNAME` record for `www`  pointing at `www.fxbits.io`
2. Wait 10-15 minutes for Github to detect the change (I tried enabling/disabling Enforce HTTPS but it didn't seem to have any effect)
3. Once Github detects the change, wait 5-10 minutes to finish generating the certificate
![image](https://user-images.githubusercontent.com/498419/114566293-c9c4e780-9c7a-11eb-9e96-bdc872e2513a.png)

4. Wait 10-15 minutes for the certificate to be applied

All in all, it took about 30 min.
Finally, it works https://www.fxbits.io redirects correctly to https://fxbits.io

**Comment by yoannchaudet** [comment] 2021-07-20 22:11
Don't hesitate to ping us (the Pages team) at https://github.community/c/github-help/github-pages if you run into issues setting up `www` variant for a custom domain. This feature shipped recently and we have been doing some work on the backend to smooth things over further.

**Closed by yoannchaudet** 2021-07-20 22:11 UTC
Labels: pages
