### ISSUE TITLE
Github Dark Theme

### ISSUE THREAD

**Issue by neev123** [isaacs/github#1793] opened 2020-05-05 07:11 UTC
I can recommend this theme if you are a 24x7 worker
https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp/reviews?h1=en

**Comment by hoshihz** [comment] 2020-05-06 01:43
Dupe of #66

**Comment by neev123** [comment] 2020-05-06 06:01
what do you mean

**Comment by Rexogamer** [comment] 2020-05-06 18:03
He means that this issue is the sam as #66 (ie the same feature request)

**Comment by TheTechRobo** [comment] 2020-07-07 14:43
@Rexogamer @hoshihz uhm but its not a feature request, it's a suggestion, saying if you want GitHub Dark Theme try this extension, it didnt ASK for the dark theme

**Comment by Rexogamer** [comment] 2020-07-07 14:52
1. This repo is specifically focused on feature requests.
2. That thread contains a lot of suggestions for extensions that will add dark mode for you so he should’ve just posted it there.
3. This thread is named poorly (_almost like it’s a suggestion_).

**Comment by TheTechRobo** [comment] 2020-07-07 16:55
@Rexogamer Good points, I never thought about it that way.

**Closed** 2020-07-12 06:14 UTC
