### ISSUE TITLE
Stacked Pull Requests

### ISSUE THREAD

**Issue by ebetica** [isaacs/github#950] opened 2017-06-05 18:13 UTC
Feature request: allow us to stack Pull Requests, so we can submit smaller pieces of code for review. An example of this is given here: https://graysonkoonce.com/stacked-pull-requests-keeping-github-diffs-small/

However, this requires you to be able to make branches in the target repository, and is highly inconvenient. Two things to making this process easier are:
- Allowing us the make a PR against another PR. 
- Allowing us to auto rebase all dependent branches when one earlier in the stack has changed.

**Comment by ebetica** [comment] 2017-06-05 18:23
I contacted Github support, and was told that they cannot tell me their roadmap, but "I will definitely add your +1 to that feature request internally."

**Comment by aspiers** [comment] 2018-04-02 19:41
Duplicate of #867.

**Comment by aspiers** [comment] 2019-02-28 14:44
Closing as duplicate: #867 is older, and #959 while newer attracted a lot of up-votes and useful debate.

**Closed by aspiers** 2019-02-28 14:44 UTC

**Comment by yairhaimo** [comment] 2020-04-27 10:55
I created a small Github app and CLI that lets you create and manage Stacked Pull Requests. I would love some feedback:
https://stacker-site.now.sh/

**Comment by aspiers** [comment] 2020-09-05 23:00
[**@yairhaimo**](https://github.com/yairhaimo) commented on [April 27, 2020 11:55 AM](https://github.com/isaacs/github/issues/950#issuecomment-619904250 "2020-04-27T10:55:12Z - Replied by Github Reply Comments"):
> I created a small Github app and CLI that lets you create and manage Stacked Pull Requests. I would love some feedback:
> https://stacker-site.now.sh/

Is there an updated link for this?  I'd be interested to try it out but the link is broken.

**Comment by yairhaimo** [comment] 2020-09-06 08:28
Should be up now, sorry. I'd love to hear any feedback, ideas, requests, complaints at stackedprs@gmail.com

**Comment by aspiers** [comment] 2020-09-06 12:44
Thanks! Might not be able to try it immediately but it's definitely on the list!
