### ISSUE TITLE
feature request: poll for issues

### ISSUE THREAD

**Issue by Darelbi** [isaacs/github#423] opened 2015-07-14 14:38 UTC
What about making possible running polls regarding each repository?

Example:

"MAINTAINER: should this feature be dropped?"
- No
- Yes

"USER: [NO] I've been using that feature here:LINK".

And answers to polls should have a desired format: "Select only one of the choices/ Select X to Y choices/ Provide a link / Allow anonymous vote / Fork it to answer the poll"

polls would have a different visibility from other tickets and would allow a more "social" interaction within github, it also gives an indirect way to see how many people is using our code and is interested in the development.

**Comment by cirosantilli** [comment] 2015-07-17 19:01
For the particular use case in your example, issue votes would be an alternative: https://github.com/isaacs/github/issues/9

**Comment by erkinalp** [comment] 2015-07-18 08:29
Affects me too? [x]

**Comment by Darelbi** [comment] 2015-07-18 10:52
yes @cirosantilli  for that particular use case yes, I think the concept needs to evolve a bit to become better both than regular poll (like in phpbb) and issue voting. Issue voting has the downside that if there are hundreds issues those will not have any visibility, so the repository owner have to choose how to give that visibility (feature an issue to be voted, or just create a poll).

**Comment by Darelbi** [comment] 2015-10-07 14:15
I think github just lost the chance to implement that, now Stackoverflow implemented teams wich basically allow "polling/voting" and much other nice things. That could have been a nice feature for github.

**Comment by GiacomoLaw** [comment] 2016-12-12 18:01
Would certainly like to see this. Especially helpful for the site I work on.

**Comment by rdwatters** [comment] 2017-07-06 19:45
More than a little awesome. Just saying: 

https://github.com/tj/gh-polls

**Comment by clarkbw** [comment] 2019-02-25 18:28
I think this is a duplicate of #221 

See also Probot polls https://probot.github.io/apps/polls/

**Closed** 2019-02-28 06:01 UTC
Labels: duplicate, enhancement, issues
