### ISSUE TITLE
GitHub Mac App can enter a bad state if sidebar is extended too far.

### ISSUE THREAD

**Issue by chadwhitacre** [isaacs/github#56] opened 2013-07-03 20:03 UTC
First reported by @shurcooL in https://github.com/whit537/github.com:

> [12 Second Video](http://shurcool.github.io/bettertogether/video/github_mac_app_resizing_bug.mov)
> 
> Easy Fix: Set a limit on how far out the sidebar can extend, to avoid this problematic state from ever occurring.
> 
> Still occurs in latest version (Future Past, 155).

**Comment by shurcooL** [comment] 2016-08-26 18:55
@whit537 can you close this issue please (or anyone with write access in this repo), it's a duplicate of #614 and has been resolved.

**Closed** 2019-02-27 04:53 UTC
Labels: bug, fixed, ui
