### ISSUE TITLE
"Resolve" button for comments

### ISSUE THREAD

**Issue by slinkp** [isaacs/github#468] opened 2015-09-18 16:07 UTC
Idea stolen entirely from google docs comments.
- You can click a "resolve" button on the comment
- The comment is then folded up and hidden
- You can still click to expand and see the original comment.

Use case: Code reviews.  When discussion goes on for a long time (eg. API changes are magnets for endless discussion), it can be very difficult to sort out which comments still need attention. Some comments are suggestions that were decided against; since the code they are commenting on hasn't changed, they stay around forever unless you delete them.   Some comments may indicate suggestions that were resolved in another way, and likewise stay visible forever because that line of code hasn't changed.  The clutter can make conclusions very difficult to see.

**Comment by slinkp** [comment] 2015-09-18 17:22
It could maybe have a GFM syntax too.  So in the source of a "resolved" comment you'd see some special marker like ... I dunno... `[*resolved*]`

**Comment by kubasub** [comment] 2015-09-22 11:48
Duplicate of https://github.com/isaacs/github/issues/251

**Comment by SilverFire** [comment] 2015-10-20 21:55
:+1:

**Comment by wbeard** [comment] 2015-10-28 21:16
:+1:

**Comment by aspiers** [comment] 2018-03-27 19:21
Since this is a duplicate, can it be closed please?

**Comment by cirosantilli** [comment] 2018-07-30 11:08
Closing as dupe as per @aspiers comment: https://github.com/isaacs/github/issues/468#issuecomment-376644004

**Closed by cirosantilli** 2018-07-30 11:08 UTC
Labels: comments, enhancement
