### ISSUE TITLE
if file isn't available (refactor/move) then offer to show history

### ISSUE THREAD

**Issue by championswimmer** [isaacs/github#1366] opened 2018-09-17 16:00 UTC
So simple example here 

https://github.com/championswimmer/vuex-module-decorators/blob/master/test/getmodule.ts

^^ this page is not available as I have moved this file. but that link is shared many places

https://github.com/championswimmer/vuex-module-decorators/commits/master/test/getmodule.ts

^^ this on the other hand is a great place to see what the file was last time it existed 

So when we go to
```
https://github.com/{org}/{repo}/blob/{branch}/path/to/file.ext
```

In the error page show a link to 

```
https://github.com/{org}/{repo}/commits/{branch}/path/to/file.ext
```

**Comment by clarkbw** [comment] 2018-10-04 11:57
I think this is a duplicate of https://github.com/isaacs/github/issues/900

**Closed** 2019-05-03 17:45 UTC
