### ISSUE TITLE
Sidebar gets squashed after visiting issues

### ISSUE THREAD

**Issue by stepantubanov** [isaacs/github#47] opened 2013-06-25 07:16 UTC
This is for new respository design.

Steps to reproduce (on this repository for example):
1. On this page (or any other issue/PR page)
2. Click "github" (the repository name in the top left).
3. This is what I get (attention to sidebar):
![2013-06-25 16 09 17](https://f.cloud.github.com/assets/1050523/701009/e5d09874-dd66-11e2-912a-085228ec60a2.png)

Note: Happens from time to time, not always.

**Comment by Mottie** [comment] 2016-06-17 02:52
@cirosantilli Is it possible this is still an issue?

**Comment by cirosantilli** [comment] 2016-06-17 07:44
@stepantubanov do you still reproduce? What browser?

**Comment by Mottie** [comment] 2016-06-17 11:27
@TPS I was asking if it is still possible because I know that originally you had to [opt-in](https://github.com/blog/2085-a-new-look-for-repositories) to see the navigation bar across the top of the page. Is there anyone out there still a hold-out and sporting the old design? Is it even possible to still have the old design?

**Comment by TPS** [comment] 2016-06-17 13:31
Ah, ok. ☺  I can't locate any other view option, unless paid/Enterprise has more of such choices than I.

**Comment by stepantubanov** [comment] 2016-06-21 11:45
@cirosantilli nope, I can't reproduce it. I think design was different back when I created the issue.

**Comment by cirosantilli** [comment] 2016-06-21 12:14
Thanks for reply, closing for now then ;-)

**Closed by cirosantilli** 2016-06-21 12:14 UTC
Labels: op-action-required
