### ISSUE TITLE
Contributions to organisations that you are not longer member of

### ISSUE THREAD

**Issue by sielay** [isaacs/github#1114] opened 2017-11-07 10:16 UTC
It's more a question of the opinion. Imagine a situation that I have been responsible for few projects which a) are open source b) are public c) are maintained by some organization (mostly some company that publish their code). After I stopped working in that organization I have been removed from their GH team. This moment my profile lacks any data about my contribution to those projects, even when 100% code was made by me and my contribution is still visible in that project to the public. I think it punishes a bit contributors for moving in their career.

**Comment by ericnewton76** [comment] 2017-12-31 20:00
Contributions should be permanent, and not tied to a database query... 👍

**Comment by sielay** [comment] 2018-01-02 21:13
Maybe they should use blockchain for it ;)

**Comment by clarkbw** [comment] 2019-03-07 18:35
Feels like this is a dupe of https://github.com/isaacs/github/issues/1138

**Comment by TPS** [comment] 2019-03-08 14:12
Yep.  _(@clarkbw You __do__ have the power to solve that, you know.…)_

**Closed by TPS** 2019-03-08 14:12 UTC
Labels: contributions-graph, duplicate
