### ISSUE TITLE
PRs should link to source repo/branch

### ISSUE THREAD

**Issue by alexreg** [isaacs/github#720] opened 2016-07-16 13:10 UTC
When you view a PR, you get .e.g `alexreg  wants to merge 3 commits into target-repo:master from source-repo:patch`. Unfortunately, neither the `target-repo:master` or `source-repo:patch` bits are links! This is silly, since there is no other good way to navigate to the source repo (or the `patch` branch specifically). I propose simply to make these links.

**Comment by timotheecour** [comment] 2017-01-15 05:06
duplicate of https://github.com/isaacs/github/issues/720

**Comment by clarkbw** [comment] 2018-03-05 22:12
duplicate of #34

**Closed by clarkbw** 2018-03-05 22:12 UTC
