### ISSUE TITLE
Can't add Collaborator by email

### ISSUE THREAD

**Issue by Grety** [isaacs/github#491] opened 2015-10-15 19:28 UTC
Says "'email' doesn't have a Github account". Although the note clearly states that email lookup is possible: "Search by username, full name or email address". Same user can be found by nickname

**Comment by cirosantilli** [comment] 2015-10-18 10:34
I reproduce: it does not work even for the public email that is shown on the profile from an URL like https://github.com/cirosantilli/test-git-web-interface/settings/collaboration

**Comment by Ramim** [comment] 2016-03-20 22:38
how is this not fixed yet ? i still cant add a collaborator by email ...

**Comment by cirosantilli** [comment] 2016-03-20 22:55
@Ramim please don't comment with +1 now that we have upvotes or else people get notified ;-)

**Comment by maxim-ge** [comment] 2016-06-10 17:57
Indeed, it does not work, please, fix!

**Comment by shm54** [comment] 2016-07-04 23:47
Yes, it does not. :( Kindly fix this or change the message in search

**Comment by TPS** [comment] 2016-07-05 04:54
Folks, don't forget to [contact __@GitHub__](https://github.com/contact) with all this concern, pointing them back to [this thread](#)!

**Comment by myintmyatkyu** [comment] 2016-09-26 03:15
Yes.. it still does not work

**Comment by tiegeng** [comment] 2017-01-19 20:52
+1, still doesn't work as of today.

**Comment by puttaa** [comment] 2017-02-11 00:12
I am checking now and it still does not work. Any ETA for the fix?

**Comment by maxim-ge** [comment] 2017-02-14 15:06
For me it worked when I filled in the "Public email" field here https://github.com/settings/profile.

**Comment by imraninbox** [comment] 2017-05-08 04:58
You'll only be able to find a GitHub user by their email address **if they've chosen to list it publicly.** Otherwise, use their username instead.

**Comment by zavidova** [comment] 2018-09-18 21:45
Same issue!

**Comment by yasuhitotanaka** [comment] 2019-03-03 02:47
me neither. I cannot also add Collaborator by email/

**Comment by Cochonours** [comment] 2019-04-15 20:15
> You'll only be able to find a GitHub user by their email address **if they've chosen to list it publicly.** Otherwise, use their username instead.

Oh, so that's why!?! It doesn't make sense as being added as a collaborator is nothing like publicly showing one's address, but whatever...

**Comment by T0TProduction** [comment] 2019-07-20 09:25
We had a similar problem just now:
Surprisingly not having a public email kept the developer from being able to join the repo as a collaborator. I invited him via his account, but GitHub showed 404 on the repo for him until he made an email public. Don't know why this is, should definitely not be this way.

**Comment by clarkbw** [comment] 2019-07-22 17:08
I think we need to close this, the email look up is working as expected.  (of course there could always be bugs)

The problem is, as [stated by](https://github.com/isaacs/github/issues/491#issuecomment-299773210) @imraninbox but I'll restate below.

The user you are inviting must have their **email address listed publicly**.  If their email address is not public the API cannot lookup the user by that email even if they have it in their account privately. You can always add users by their GitHub account name if the email address doesn't work.

**Closed by clarkbw** 2019-07-22 17:08 UTC
Labels: bug, search

**Comment by chaowu2009** [comment] 2020-03-11 02:16
got the same problem. Could not find the user using their email address.
