### ISSUE TITLE
Replace "paper cuts" with a project like "github"

### ISSUE THREAD

**Issue by rektide** [isaacs/github#1339] opened 2018-08-28 21:12 UTC
Github recently introduced a custom thing called "Project Paper Cuts" to solicit advice for what needs to be improved: https://mobile.twitter.com/github/status/1034523814867034112

Instead, I would like github to offer a repository where people can file issues & have them tracked. For example, https://github.com/isaacs/github/ .

**Comment by rektide** [comment] 2018-08-28 21:14
Hat tip to @humphd on this #dogfood ing idea:
> However, can't help wonder why there isn't a repo we can file issues in directly.  Embrace what you've built, GitHub!
https://mobile.twitter.com/humphd/status/1034544899033628673

**Comment by TPS** [comment] 2018-09-02 04:32
@isaacs @cirosantilli Did y'all see the above & https://blog.github.com/2018-08-28-announcing-paper-cuts/, complete w/ link to ___this___ repo⁉️ We _legit_ now. 🕺😜

@lukehefson Honestly, the largest "paper cut" _by far_ (I'll spare you the graphic nature of what this would be in medical-trauma terms) is everything OP states, above.

**Comment by TPS** [comment] 2018-09-02 04:36
Also, this duplicates #6! :bow:

**Comment by cirosantilli** [comment] 2018-09-02 04:56
Closing as dupe of #6 

So, when do they start paying me? :-)

Most likely scenario is they eventually create the damned https://github.com/github/github issue tracker, and then all my amazing contribs will be forgotten.

lololol

**Closed** 2018-09-02 04:57 UTC

**Comment by TPS** [comment] 2018-09-02 05:10
Of course, if y'all @GitHub are _serious_, transfer ownership of the repo, but keep (& [expand](https://github.com/isaacs/github/issues/619) _hint, hint_ 😜) the community mods.

@cirosantilli You better send a résumé/CV to @lukehefson this very instant.  (I suppose a detailed list of all those "amazing contribs" may not be enough.…  I suppose Microsoft has _some_ standards, amirite? 🤣)
