### ISSUE TITLE
Feature to follow organisation as well like following a user

### ISSUE THREAD

**Issue by AkarshSatija** [isaacs/github#916] opened 2017-03-29 08:46 UTC
A feature to follow organisations so as to see their updated in all the repos they have.

Inside that it should actually start following all the users in that organisation so as to create my feed

**Comment by Mottie** [comment] 2017-03-29 17:22
Duplicate of #50

**Closed** 2017-03-30 00:32 UTC

**Comment by AkarshSatija** [comment] 2017-03-30 04:59
@Mottie I did search for it before adding an issue, but couldn't find it. Anyways closing this.
Thanks :)
