### ISSUE TITLE
Allow assignment of issues to non-collaborators

### ISSUE THREAD

**Issue by patcon** [isaacs/github#100] opened 2013-09-17 15:29 UTC
Context: https://github.com/drush-ops/drush/pull/88#issuecomment-24595732

Currently, if a potential contributor want's to publicly assign themselves to a particular issue, they apparently must be granted push access to the repo. This makes it difficult for a potential contributor to "bookmark" an issue for later effort, making full use of this issue listing:
https://github.com/dashboard/issues/assigned?direction=asc&sort=updated&state=open

(Alternatively, "push" access collaborators should also be able to assign issues to themselves. Specifically reticketed this is #153)

cc: @greg-1-anderson

(Sent an email to support@github.com. Will publish response here. Whoop whoop!)

**Comment by ThomasAy** [comment] 2015-03-13 16:22
I would *love* this :+1:

**Comment by PhantomYdn** [comment] 2015-04-09 20:59
Fully agree with this request :+1:

**Comment by mgechev** [comment] 2015-05-20 13:05
:+1:

**Comment by aniav** [comment] 2015-06-04 23:37
Definitelly would want that!

**Comment by craftworkgames** [comment] 2015-08-02 22:33
:+1:

**Comment by ldemailly** [comment] 2015-08-12 21:12
want ! ty

**Comment by PanosSakkos** [comment] 2015-11-08 19:11
:+1:

**Comment by elennick** [comment] 2015-12-05 20:16
+1

**Comment by thejmazz** [comment] 2016-02-07 03:52
+1

**Comment by rbeauchamp** [comment] 2016-02-08 05:20
+1

**Comment by dolftax** [comment] 2016-02-08 09:40
:+1:

**Comment by floydpraveen** [comment] 2016-02-09 06:23
+1

**Comment by rahulcs** [comment] 2016-02-09 06:23
:+1:

**Comment by fazam** [comment] 2016-02-09 17:50
+1

**Comment by siddharthist** [comment] 2016-03-04 06:56
:+1:

**Comment by f-w** [comment] 2016-03-18 17:04
:+1:

**Comment by usirin** [comment] 2016-03-31 18:03
:+1:

**Comment by gokmen** [comment] 2016-03-31 18:03
:+1:

**Comment by tpiha** [comment] 2016-03-31 18:15
:+1:

**Comment by hakankaradis** [comment] 2016-03-31 18:51
:+1:

**Comment by DinisCruz** [comment] 2016-05-13 12:31
Any updates, I really could do with this, since I don't want to give them access to push into the repo (all collaborators are working from forks)

**Comment by GeoffreyEmerson** [comment] 2016-06-25 20:54
I'm honestly surprised this isn't a feature, and I don't see anybody even proposing a work-around. My teammates all have forks, and I can't assign anything to them without giving them push access. Can something like this be done with the paid github version?

**Comment by AlexMassenzio** [comment] 2016-08-05 16:37
+1

**Comment by bazzilic** [comment] 2016-09-09 09:59
Seriously, it's been three years. Is this such a big issue?

**Comment by jlevy** [comment] 2016-10-25 01:12
This is a serious friction when managing popular projects with lots of contributors who volunteer to help in small ways. Has anyone found a workaround?

**Comment by DinisCruz** [comment] 2016-10-25 11:41
Yes I still have this problem, work arounds would be great

**Comment by AustinDidierTran** [comment] 2016-12-18 03:08
Can't they just give different access levels to collaborators? Do we really need to use an external service only because of this? 🤔

**Comment by Fuco1** [comment] 2017-04-11 13:46
Well, the workaround is "obvious": fork, duplicate the issue in your fork and add a link to the parent repo, do all the discussion in the parent and handle state in the fork.  You would still probably have to grant access to the "master" in your fork so they can coordinate.

Also, one day the Sun will engulf the Earth so this doesn't matter anyway...

**Comment by TPS** [comment] 2017-04-11 15:01
>Also, one day the Sun will engulf the Earth so this doesn't matter anyway.…

@Fuco1 [You forgot the obligatory XKCD, so folks know what you mean! 😂](https://m.xkcd.com/1822/:)

![XKCD 1822](https://imgs.xkcd.com/comics/existential_bug_reports.png)

**Comment by MasterYushi** [comment] 2017-05-24 21:21
Please add this already

**Comment by DraqueT** [comment] 2017-07-11 17:50
Good lord, how is such a basic issue not yet implemented?

**Comment by orourkedd** [comment] 2017-07-28 19:19
+1

**Comment by xasetl** [comment] 2017-08-07 17:50
+1

**Comment by Slivo-fr** [comment] 2017-08-11 12:14
+1

**Comment by AlexWayfer** [comment] 2017-08-11 12:40
Please stop writing new comments with `+1` and :+1:, you notify dozens of other people about your wordless opinion. Put your finger up in the first comment, that's enough.

**Comment by salameer** [comment] 2017-09-24 08:01
Hello all,

So I've been struggling with this myself and what I'm planning to do is to build a bot or application that:
- Has a github account with "write privilege"
- listens to all comments add to issues in my repo.
- if a magic word for example "assign this issue to my alias" shows up in a comment then assign to the author of that comment.

might be risky, and you'll need to spread awareness about this in your repo but atleast can get the Job done

Hope this suggestion helps :)

**Comment by FlamesRunner** [comment] 2017-10-08 01:24
+1

Sigh, I'm starting to think "internal feature list" is lingo for "ignore list."

**Comment by patcon** [comment] 2017-10-16 00:05
@salameer it's done already! https://github.com/isaacs/github/issues/153#issuecomment-324964752

:)

**Comment by ericblade** [comment] 2017-11-29 23:50
IMO, this makes the issue tracker kind of a pain in the butt -- might as well use a dedicated issue tracker if you can't assign other people.  Perhaps limit it to anyone who's done anything in the project, comments, PRs, etc

**Comment by cagdasgerede** [comment] 2017-12-30 18:15
+1

**Comment by wanderingstan** [comment] 2018-01-07 13:39
👍

**Comment by Hrabal** [comment] 2018-01-28 13:06
+1

**Comment by joannakl** [comment] 2018-02-17 13:54
+1

**Comment by nileshgulia1** [comment] 2018-02-19 20:41
+1

**Comment by jadonk** [comment] 2018-04-24 18:27
grrr

**Comment by IvanMalison** [comment] 2018-05-15 21:27
> Please stop writing new comments with +1 and , you notify dozens of other people about your wordless opinion. Put your finger up in the first comment, that's enough.

While I agree with the sentiment here, I have to leave a comment here because of #283 (or else I won't be able to easily find this issue later)

**Comment by AlexWayfer** [comment] 2018-05-16 07:26
> While I agree with the sentiment here, I have to leave a comment here because of #283 (or else I won't be able to easily find this issue later)

Thanks, I'll know.

**Comment by SteveALee** [comment] 2019-01-04 19:45
Now people can find issues labled 'Help Wanted' and offer help they need to be assigned the issue even if can only supply a PR

**Comment by kkm000** [comment] 2019-03-23 17:56
This issue started its long life in 2013, and has been open for 2013 days as of today (just a little over five and a half years). Happy ~~birthday~~ utterly irrelevant numerical coincidence, our dear senior feature request! 🍾🍾🍾 Hope your life is comfortable on the internal feature list--you must have hundreds of friends there!

I sincerely wish you be taken care of during the next 5.5 years! If you and #1131 are both fixed before the Sun engulfs the Earth, we'll even be able to track our issues on GitHub, not on napkins, grocery receipts and banana peels, as we do it now!

**Comment by clarkbw** [comment] 2019-04-05 04:43
We're looking into this.  Being able to assign anyone randomly is an abuse vector because I can create an issue with an abusive title and assign a person to it to harass them.  To prevent this we're likely to require that a person has interacted with repository in some fashion via commits or commenting in an issue; a low enough bar that limits abuse.

**Comment by kkm000** [comment] 2019-04-05 04:58
@clarkbw, thank you, I think this is a great idea! No additional setup, no need to add collaborators to a list, or do anything at all. Super!!! I would love to see it implemented this way!

**Comment by yatil** [comment] 2019-04-05 08:14
@clarkbw That would be incredibly useful for us at @w3c. Maybe just allowing it for organizations and not for individual repositories could be another way to limit the abuse vector. (Thanks for thinking about that, btw., it is an important consideration!)

**Comment by bazzilic** [comment] 2019-04-05 08:37
@yatil Bulletproof plan. These stupid spammers and abusers will never figure out how to create an organisation!

@clarkbw Great to hear that you guys are working on this! If a person follows/starred a repository, wouldn't this be enough for the repo owner to be able to assign issues to them?

**Comment by TPS** [comment] 2019-04-05 11:27
@clarkbw I don't quite understand how that abuse potential isn't easily averted:  Wouldn't a simple invitation system solve it? (That's not saying the backend would be easy!)  E.g., a user w/ rights assigns whomever.  Said whomever receives UI/e-mail invite to accept assignment to issue.  If declining, _can_ do so semi-permanently (like "Block Users" UI, easily reversible) per inviter/repo/org/whatever.

**Comment by clarkbw** [comment] 2019-04-05 12:18
@tps that system is elegant even through it takes some backend work. The issue is then with notifications. Imagine I keep creating issues with the title “TPS is stupid” and you get those in your inbox. You could imagine a 1 step abstraction where we notify you of an invitation without the title. But eventually you’ll need to see the title or content to know it’s valid. Blocking at this stage is valid and means you should only see this thing once. But our research so far shows that assigning to someone who has never participated in the repo at all is a very low  occurrence event. It seems like a good compromise to ask that someone participate even a little before they can be assigned. Perhaps later we’ll find you’re right and we need to expand it, but that’s ok; we can do that after. Or further research could change our minds now. Still investigating.

**Comment by TPS** [comment] 2019-04-06 12:04
@clarkbw I agree an assignee should've had _some_ interaction w/ the repo/org/assigner/whatever.  But I believe that invitation system is necessary on _top_ of that, perhaps w/ __Settings__ toggles:
>- [ ] Allow invitations to issue assignment when I:
>    - [ ] Open
>        - [ ] PR
>        - [ ] issue
>    - [ ] When I comment in:
>         - [ ] repo
>         - [ ] org
>         - [ ] reply to [user w/ appropriate rights, whatever's that's called 🤔]
>     - [ ] have no relationship whatsoever [default ___OFF, please___]

**Comment by kkm000** [comment] 2019-04-07 00:52
@TPS, an invitation system is a non-starter. With it, instead of tracking issue assignment to non-members on banana peels, I would be tracking (a) invitations to non-members to become "assignees" sent/responded/unresponded on banana peels, and also (b) issues assigned to non-bemebers who blocked the invitation with your battery of checkboxes. Look, you just stabbed the whole idea in the heart.

As I understood @clarkbw's idea, I would be able to assign the issue the guy who said "Ok, I'm taking it" so I do not lose track of the ticket. If the guy never said anything in my repo, I won't be able to assign the issue (nor do I want to).

Besides, I would call someone who first posts a message "ok, I'll do that" and then cuts all communication not an “extraordinarily privacy-conscious user”, but rather “a windbag.” I do not think we need a special checkbox for this.

**Comment by TPS** [comment] 2019-04-07 03:05
Well, @kkm000 & @clarkbw, IMHO, you can't have absolutely both @ the same time: either this will be convenient (for assigners) or protecting from abuse (for assignees).  I'd advise _defaulting_ those suggested settings above as y'all mentioned for assigner's convenience, but notifying assigners _immediately_ upon assignment if the assignee's preferences prevent such (since I expect most folks to leave defaults mostly as-is).  _(N.B.: I added an additional toggle to the above settings mockup for those who'd **like** willy-nilly assignment! 🤷🏾‍♂️)_

Besides, @kkm000, assigning an issue shouldn't prevent an assignee **un**assigning themselves, nor does it ensure that they'll actually accomplish the assignment!  Any which way, the assigner _still_ has the responsibility to check on progress, even if they're not actually expecting to do whatever themselves!

**Comment by mekarpeles** [comment] 2019-05-02 18:40
Been hoping for this for months:
1) request to be assigned to an issue (without having read / write access)
2) ability to assign someone to an issue (or at least invite w/o them having read / write access)

> We're looking into this. Being able to assign anyone randomly is an abuse vector because I can create an issue with an abusive title and assign a person to it to harass them.

I don't buy it. Such abuse can and likely does happen anyway as one can tag anyone in such issues as described. People who abuse the system should be labeled as abusers and this shouldn't be a limiter on effective user experience for the "rest of us".

> To prevent this we're likely to require that a person has interacted with repository in some fashion via commits or commenting in an issue; a low enough bar that limits abuse.

This doesn't prevent any attack vectors. The reason a person is getting assigned to a task is presumably an admin on the project is vouching for the user (unless the user is attempting to assign themselves, which perhaps would require approval).

I think the egregious case is where a user doesn't *want* to be associated with a project or an issue, in which case there should be a *separate feature* for a patron to block a project or an account and sidestep this problem completely. These two use cases shouldn't be conflated together -- both problems should be solved independently and not to each other's exclusion. Security not at the expense of making it easy for new patrons to meaningfully contribute and feel welcomed in a community.

Idea: Why not pending Assignees? Show "User Assigned [pending]".

Right now one can work around this by creating `Assigned-to: @person` labels which ~feels like~ is a complete hack.

**Comment by alallier** [comment] 2019-06-25 18:23
GitHub now allows you to [assign issues to issue commenters](https://github.blog/2019-06-25-assign-issues-to-issue-commenters/)

**Closed** 2019-06-26 02:14 UTC
Labels: WIP, issues, pull-requests, ui

**Comment by scottcwilson** [comment] 2020-07-15 18:57
It would be great if we could go one step further and be allowed to assign issues to anyone who has contributed to the project.  Right now it's three steps (ask them to comment, they comment, you assign); would be better if it was one step.

**Comment by mistercrunch** [comment] 2020-10-16 06:01
Looks like giving the `Read` role allows assigning issues to them. 
<img width="753" alt="Screen Shot 2020-10-15 at 11 00 01 PM" src="https://user-images.githubusercontent.com/487433/96218761-3ebc9c00-0f3a-11eb-98a9-b3d0c129a782.png">
[source](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization)

Not the ideal solution in all cases, but it may work for some of the people who commented here.

**Comment by TPS** [comment] 2020-10-16 11:17
@mistercrunch Sadly, this seems available _only_ among members of the _same_ org, so no cross-/non-org assignment via this `read` permission.  It'd be great to have this ability expanded _globally_!
