### ISSUE TITLE
Add +1/helpful for comments.

### ISSUE THREAD

**Issue by kenorb** [isaacs/github#509] opened 2015-11-04 11:27 UTC
Some issues/commits have [hundreds of comments](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac), so I think it would be useful to have a flag to each comment (like +1 or *helpful*). In this case, we can see which comments were the most useful/helpful.

For example having some long *won't fix* issue, it'll be good idea to see which comments provided the best workaround which has been reported as the most useful.

Further more long threads could be sorted by the most relevant.

**Comment by cirosantilli** [comment] 2015-11-05 11:06
Possible duplicate of: https://github.com/isaacs/github/issues/209

**Closed** 2015-11-05 11:25 UTC
Labels: comments, enhancement
