### ISSUE TITLE
Associate email address with organization for author field on new commits

### ISSUE THREAD

**Issue by charlieok** [isaacs/github#95] opened 2013-09-09 22:20 UTC
I love the “custom routing” feature in https://github.com/settings/notifications , which allows me to configure notification email addresses depending on which organization owns a repository.

The problem I'm having is that this is restricted to outgoing notification emails. I'd like to take this association farther. Specifically, to the author email on commits generated via Github's browser interface.

Our workflow involves merging story branches into master (or other long-running branches) inside Github, when the merge button is green. If I do this however, the merge commit doesn't get my email address for that organization. Instead, it gets my primary email address. This affects other applications integrated with git/github. For example, it affects Travis CI, which sends build success or failure emails to my personal email address instead of my organization email address.

**Comment by taavi** [comment] 2015-01-16 16:50
:+1:

**Comment by fstehle** [comment] 2015-01-19 18:26
:+1:

**Comment by yoyko** [comment] 2015-02-25 09:34
+1

**Comment by minterior** [comment] 2015-02-27 11:03
+1

**Comment by dpcat237** [comment] 2015-02-27 11:07
+1

**Comment by egcastro** [comment] 2015-02-27 11:11
+1

**Comment by jonmoter** [comment] 2015-03-06 17:28
+1

**Comment by muniere** [comment] 2015-03-27 04:04
+1

**Comment by vchernomor** [comment] 2015-03-30 15:00
+1

**Comment by srcoley** [comment] 2015-04-30 16:06
+1 GitHub please...

**Comment by AlexOverbeck** [comment] 2015-04-30 16:08
+1

**Comment by gnmerritt** [comment] 2015-06-23 19:06
+1

**Comment by claudusd** [comment] 2015-07-02 15:26
+1

**Comment by designedbyz** [comment] 2015-07-14 20:29
+1

**Comment by rshk** [comment] 2015-08-13 10:09
:+1:

**Comment by rolebi** [comment] 2015-08-26 10:11
:+1:

**Comment by dagezi** [comment] 2015-09-02 03:50
+1

**Comment by delind** [comment] 2015-10-12 20:39
:+1:

**Comment by navi7** [comment] 2015-11-04 10:20
Any news on when (and if) this will be implemented?

**Comment by grundleborg** [comment] 2015-11-15 14:29
+1

**Comment by anmij** [comment] 2015-12-16 15:54
+1

**Comment by rhansen** [comment] 2016-01-14 20:46
:+1:

**Comment by rhansen** [comment] 2016-01-14 23:03
I emailed support@github.com about this.  Here is their response:

> Thanks so much for taking the time to write in with details on your use case for this, it does sound helpful, and I'll definitely pass that on to the team to consider.

**Comment by charlieok** [comment] 2016-01-14 23:10
wow, I wrote this request over two years ago. Thanks for the +1 collection everyone :-/

**Comment by k06a** [comment] 2016-01-29 12:26
:+1:

**Comment by faudebert** [comment] 2016-02-08 11:29
:+1:

**Comment by iiegor** [comment] 2016-02-08 19:25
+1

**Comment by npinchot** [comment] 2016-03-24 16:31
:+1:

**Comment by charlieok** [comment] 2016-03-24 16:37
so... I see another :+1: was added as a comment. We don't do that on github anymore! Now there are emoji reactions :smile:

**Comment by navi7** [comment] 2016-03-24 16:39
Yeah, but then you don't get an email pestering you about it :)

**Comment by sandstrom** [comment] 2016-03-24 22:26
:+1:

(adding a comment will also have this issue sort higher in the list, when sorting on 'most commented')

**Comment by charlieok** [comment] 2016-03-24 22:41
well then [github's response](https://github.com/dear-github/dear-github/pull/115/commits/4afa490932578027462f2a8f404a38adace02f16) to the ['dear github' letter](https://github.com/dear-github/dear-github) doesn't seem to have quite solved the issue of :+1: comments if people are still so motivated to leave them :frowning:

**Comment by nweisenfeld** [comment] 2016-03-29 20:53
:+1:

**Comment by Brunty** [comment] 2016-04-08 13:38
:+1:

**Comment by netpro2k** [comment] 2016-04-26 18:20
:+1:

**Comment by benoror** [comment] 2016-05-03 01:13
+1 👍

**Comment by magat** [comment] 2016-05-20 10:01
👍

**Comment by s-petit** [comment] 2016-05-20 10:03
:+1

**Comment by aromanet42** [comment] 2016-05-20 12:57
+1 :+1:

**Comment by Indy2222** [comment] 2016-06-15 14:36
:+1:

**Comment by sschaetz** [comment] 2016-06-17 20:55
:+1:

**Comment by cmey** [comment] 2016-06-17 21:03
👍

**Comment by johanarnor** [comment] 2016-07-07 08:25
+1

**Comment by dai0304** [comment] 2016-07-28 15:40
*1

**Comment by seumac** [comment] 2016-08-23 09:51
:+1:

**Comment by k06a** [comment] 2016-09-14 11:03
👍

**Comment by vikmary** [comment] 2016-09-14 11:05
👍

**Comment by arkichek** [comment] 2016-09-14 11:06
👍

**Comment by k06a** [comment] 2016-09-19 10:27
![](https://raw.github.com/ML-Works/webhook-proxy/master/resources/crutch.jpg)

Our team has just invented workaround for this issue: https://github.com/ML-Works/webhook-proxy

Main idea is to proxy push-webhooks from GitHub and replace emails by the desired way.

**Comment by djui** [comment] 2016-09-27 09:06
Any updates on the priority on this issue? I'm also fine with a "won't fix" but clarity trumps uncertainty. We would like to avoid having to invent workarounds like the webhook-proxy.

**Comment by joelochlann** [comment] 2016-09-29 13:57
👍

**Comment by jerryhebert** [comment] 2016-10-25 17:09
https://gist.github.com/BPScott/1366790

**Comment by garrettrayj** [comment] 2016-11-09 15:47
👍

**Comment by wwwdata** [comment] 2016-11-16 17:36
I have this issue for years now as well. I could always avoid it by simply using the `hub` tool on the command line. But with the new `squash and merge` feature, which is not already supported in `hub`, things get complicated. I can manually squash and push the commit, but then the PR is not closing for me like when pushing a manual merge on the terminal. It's totally no option for me to commit with my private email address to company repos. Because build systems send emails to my private email address then and it get's mixed up with correct commits from the company email address.

**Comment by tsaodown** [comment] 2017-02-16 04:27
👍

**Comment by nokite** [comment] 2017-03-23 13:40
I communicated to the GitHub support. They let me know that this functionality is not yet implemented, but the issue is on their radar. They gave me no promises, but said that they'll pass my +1 for this feature.

**Comment by nahpeps** [comment] 2017-07-03 13:22
:+1:

**Comment by oBusk** [comment] 2017-08-24 15:05
+1

**Comment by dcow** [comment] 2017-08-28 23:30
We are always evolving our tooling and processes around repository management. Some of our discussions and proposed solutions boil down to, "we'd love to do X but cannot currently require it because that would require people to use the web ui for generating commits" aka it's a tooling limitation. People on the team are encouraged to use their personal account with their work email set for org-scoped projects so things like contribution attribution works and generally to enjoy the experience a social Github workflow enables (otherwise we'd all just use work accounts and be done with it). 

It's surprising that things like additional ssh keys and gpg signature verification work as you'd expect but effectively setting a git configuration value that doesn't have any adverse implications would be so difficult to implement. It's quite a silly issue to let negatively affect the product user experience and probably the only reason our team has not adopted a more GH-dependent (vs git) workflow.

**Comment by DuBistKomisch** [comment] 2017-10-06 08:54
:+1: have to merge PRs on the command line to get the right email, seriously?

**Comment by adam-arold** [comment] 2018-04-18 14:44
+1 Any progress with this? I desperately need this, maintaining multiple profiles is PITA.

**Comment by mistyhacks** [comment] 2018-05-31 17:57
When using the web UI, you can now choose the email address to use per commit, from a drop-down. However, it is impossible (apparently) to set a default per organization. I went looking for a setting to do this, but it doesn't seem to exist, and I ended up here instead.

**Comment by alexvy86** [comment] 2018-06-18 21:34
You can do this now for individual commits as @mistyhacks said, but apparently still can't when merging Pull Requests. And as others have mentioned, being able to change the default per organization would be really nice to have.

**Comment by tombigel** [comment] 2018-07-11 14:18
+1
@alexvy86 @mistyhacks You cant do this for pull requests though

**Comment by zayass** [comment] 2018-07-13 20:30
Why this is working for commit but not for merge.
Merging PR with web UI is much more common than write code in browser I think.
It is very uncomfortable to use same account for work and personal use because of this issue.

**Comment by vladimirpetrovski** [comment] 2018-09-24 09:02
+1

**Comment by jerolba** [comment] 2018-10-09 08:05
+1

**Comment by amanfredi** [comment] 2018-10-19 21:20
+1

**Comment by aholovko** [comment] 2018-10-20 08:06
+1

**Comment by joaoe** [comment] 2018-11-06 09:08
This is a very serious issue for me, also because I'm part of two organizations and my personal email is being attached to stuff that is not even my property.

**Comment by EduardSergeev** [comment] 2019-01-29 05:34
> Our team has just invented workaround for this issue: https://github.com/ML-Works/webhook-proxy

Unfortunately it isn't possible to fix github commit with this approach, is it? Looks like you just replace the committer email before passing it to external system (like `youtrack`).

**Comment by YoavGaudin** [comment] 2019-01-31 14:16
+1
Any news?
I tried using `hub` to create pull requests from the command line. 
But unfortunately, those pull requests do not benefit from the template initial description.

**Comment by garretwilson** [comment] 2019-02-02 17:33
We're considering using GitHub more than we do now because Bitbucket has a huge problem: they use an email for a login identifier, which ties the account to some company and causes all sorts of problems. GitHub seems to have a better approach: a single login ID, independent from any company, and I can add as many emails as I like. Great.

But now it seems that GitHub still ties me to a single address for many web-based commits, e.g. merging pull requests? I can't associate emails with organizations, so that when I merge a pull request for a particular organization, it always uses the correct email? That's a bummer, and suddenly puts me back in the same boat as Bitbucket.

Please let us associate web-based commit emails with different repositories and different organizations. Thank you.

**Comment by nycgavin** [comment] 2019-02-08 18:03
Facing the same exact issue with my team

**Comment by TPS** [comment] 2019-03-26 01:23
I think https://github.blog/changelog/2019-03-25-view-organization-members-email-addresses/ might be considered progress toward this, as it seems like work toward being part of the infrastructure necessary to implement it.

**Comment by gallexi** [comment] 2019-04-24 19:10
![Good News Everyone meme from Futurama](https://user-images.githubusercontent.com/17116584/56686321-969d7e00-6688-11e9-9874-b494a5dc5c08.png)

You can now specify your git commit email when merging a PR!!
See more: https://github.blog/changelog/2019-04-24-choose-your-merge-commit-email/

**Comment by garretwilson** [comment] 2019-04-24 20:20
This is a great step, thanks!

I think ideally it would be nice to be able to set the email address on a per-project basis, so that the merge requests would automatically default to the correct email address. This is not an outlandish idea; we can already do the same thing locally on a per-repository basis using the following Git command (leaving off `--global`):

```
git config user.email "email@example.com"
```

But [this new option](https://github.blog/changelog/2019-04-24-choose-your-merge-commit-email/) is a great intermediate step. Thanks again for implementing it.

**Comment by benbalter** [comment] 2019-04-24 21:34
@garretwilson the drop down will default to the last email you used to commit to the repo, defaulting to your organization notification email if this is your first commit, meaning ideally, it should default to the email you'd like to use for the repo, or will after your first use, without needing to manage an additional setting.

**Comment by adam-arold** [comment] 2019-04-25 12:31
# This is awesome!

**Comment by clarkbw** [comment] 2019-04-25 18:29
Thanks for the all the feedback!  If you have concerns or find bugs leave them here and contact support.  If there are followup features you'd like to see please open a new issue and tag this one.

🚢 https://github.blog/changelog/2019-04-24-choose-your-merge-commit-email/

**Closed by clarkbw** 2019-04-25 18:29 UTC
Labels: email, implemented, merge, pull-requests

**Comment by nycgavin** [comment] 2019-04-25 20:54
Thank you for doing this!

**Comment by DrLeh** [comment] 2019-05-02 15:07
@benbalter 
> the drop down will default to the last email you used to commit to the repo, defaulting to your organization notification email if this is your first commit, meaning ideally, it should default to the email you'd like to use for the repo, or will after your first use, without needing to manage an additional setting.

It seems to always be defaulting to my first email, I'm having to change it every time. If I push a commit directly (aka not through a PR), is it associating to my first email instead and resetting this? Would be nice if there was a way to just configure this for my repo and force a value to be the default

**Comment by garretwilson** [comment] 2019-05-02 15:12
> I think ideally it would be nice to be able to set the email address on a per-project basis …

After I suggested that (noting that this is already available in Git locally), I realized that the more important things would be to associated the email with the organization itself, or at least specify a _default_ for each organization. And now I realize that this is _exactly what this ticket originally requested_! 😆 So good work, but let's not forget semantics. Thank you!

**Comment by Kaapelikala** [comment] 2019-05-07 12:39
Thank you for this! Makes working for several different organisations much easier without the need to change global settings all the time.

**Comment by gallexi** [comment] 2019-05-07 16:18
> If I push a commit directly (aka not through a PR), is it associating to my first email instead and resetting this?

@DrLeh if you commit to a repository via any means (make a commit locally and push to the repo on GitHub, or make a commit through the online editor), the email used to make that commit will be the one that these features default to next time.

Hope this helps! If you're still experiencing this issue, please feel free to reach out to GitHub Support so we can investigate this further =]

**Comment by DrLeh** [comment] 2019-05-08 15:26
@gallexi yeah it's not working for me. I have two emails configured A and B
1. Open PR 1, email dropdown is set to B.
2. Change email dropdown to A, my desired email for this project
3. Merge the code via a Squash and Merge
2. Open PR 2, email dropdown is still set to B.

**Comment by benbalter** [comment] 2019-05-09 21:47
@DrLeh Had a chance to dig into this a bit more and wanted to share two scenarios where I believe the drop down may not reflect the last email used _in the drop down_:

1. When after merging, commits are pushed to any branch using a different email.
2. When squash merging another user's pull request

The reason for both is that we look for the most recent commit, on any branch, that you _authored_. 

If you've authored other commits since the last merge via the web interface using another email, those commits will override the preference. 

Similarly, if you squash merge another user's pull request, the actor is set as the committer and the PR author is set as the commit author (for proper attribution), in which case the email you selected via the dropdown for that squash merge (of another user's pull request) would not be preserved and it would default to your most recent authored commit or your per-organization notification email, if set.

/cx https://github.com/todogroup/gh-issues/issues/32 for a similar discussion.

**Comment by DrLeh** [comment] 2019-05-09 22:12
@benbalter I figured that might be the case. I tried doing a merge commit instead of a squash and that fixed it, I didn't get a chance to respond here yet. Thanks!

**Comment by glenpike** [comment] 2019-05-10 12:38
Please can we have it default to the organisation's email for squash merges too? 

I have a scenario where I'm the only committer of several commits in a PR and when I go to squash, it's still not defaulting to the correct default email for the organisation (even though this is the email used for each commit in the log).

**Comment by jlevon** [comment] 2020-01-28 11:12
This doesn't work when doing a (squash) merge via the API

**Comment by StefanoFioravanzo** [comment] 2020-02-09 16:00
I don't see the email dropdown anymore when trying yo squash or merge commit a PR! I am sure it was there a few weeks ago, but now I am not prompted with the drop down anymore. I am committing PRs that I have authored with my organisation address, but they now appear with my personal address when squashed.

**Comment by Sequoia** [comment] 2020-03-05 20:17
Will try to repro but I am fairly certain my github UI keeps defaulting back to my main (personal) email. At work I merge PRs 5-10 times/week, I have been doing no side-projects at all lately so I know I've never set it back to my personal email. I have definitely set it to my work email (upon clicking "squash and merge") *several times* and *never* set it back to my personal email. I keep getting personal email selected.
